import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import nextPlugin from '@next/eslint-plugin-next';
import reactHooks from 'eslint-plugin-react-hooks';

/**
 * Lint had never run on this codebase: next.config.mjs set
 * `eslint.ignoreDuringBuilds: true` and no config file existed.
 *
 * The rules that earn their keep here are react-hooks/exhaustive-deps (which
 * flags the stale-closure family — the countdown effect that captured an empty
 * `questions`, and the heartbeat effect that remounted on every keystroke) and
 * no-unused-vars (~60 dead imports were shipping to the client).
 *
 * eslint-plugin-react-hooks v7 also ships several much newer, more opinionated
 * rules — set-state-in-effect, refs-during-render, purity. They flag real
 * patterns, but ones this codebase predates and which are a separate
 * refactor from a bug-fix pass. They are warnings so they are visible without
 * turning `npm run lint` into a wall of red that nobody reads.
 */
export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'data/**',
      'public/**',
      'drizzle/**',
      'next-env.d.ts', // generated by Next, edited by nobody
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // Build/CLI scripts run in Node, not the browser.
  {
    files: ['scripts/**/*.{mjs,ts}', '*.config.{mjs,ts}', 'vitest.config.ts'],
    languageOptions: {
      globals: { console: 'readonly', process: 'readonly', __dirname: 'readonly' },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },

  {
    files: ['src/**/*.{ts,tsx}'],
    plugins: {
      '@next/next': nextPlugin,
      'react-hooks': reactHooks,
    },
    languageOptions: {
      globals: { console: 'readonly', process: 'readonly' },
    },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      ...reactHooks.configs.recommended.rules,

      // The two that catch this codebase's actual bug classes.
      'react-hooks/exhaustive-deps': 'warn',
      'react-hooks/rules-of-hooks': 'error',

      // Newer v7 rules — informative, but pre-existing and out of scope for a
      // bug-fix pass. Left visible rather than switched off.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/immutability': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn',
      'react-hooks/static-components': 'warn',
      'react-hooks/incompatible-library': 'warn',
      'react-hooks/set-state-in-render': 'warn',

      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],

      // A handful of DTO boundaries genuinely take shape-unknown JSON.
      '@typescript-eslint/no-explicit-any': 'warn',

      'preserve-caught-error': 'warn',
      'no-useless-assignment': 'warn',

      // FBR-04: the exam runner's fullscreen barrier read a bare `status`
      // identifier that resolved to the DOM global `window.status` (a legacy
      // `string`, always ''), so `status === 'in_progress'` was always false
      // and the barrier never rendered for any student on any platform. This
      // typechecks cleanly — lib.dom.d.ts declares `status` on `Window` — so
      // tsc cannot catch it. These globals are exactly the ones easy to
      // shadow-by-accident in a component; this rule would have caught the
      // line at build time.
      'no-restricted-globals': ['error', 'status', 'name', 'length', 'event', 'closed'],
    },
  },
);
